InsightAvionics/Models/ProductUpdateVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace InsightAvionics.Models
{
    public class ProductUpdateVM

    {
        [Key]
        public int ID { get; set; }

        public IList<Update> Updates { get; set; }
        public IList<Product> Products { get; set; }

    }
}

InsightAvionics/Controllers/SideProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InsightAvionics.Models;
using UploadAndDisplayImageInMvc.Repositories;

namespace InsightAvionics.Controllers
{
    public class SideProductsController : Controller
    {
        private InsightAvionicsContext db = new InsightAvionicsContext();

        // GET: SideProducts
        public ActionResult Index()
        {
            return View(db.SideProducts.ToList());
        }

        public ActionResult Short(string shortname)
        {
            SideProduct sp = db.SideProducts.Where(p => p.SideShort == shortname).FirstOrDefault();
            if (sp != null)
            {
                return View("Details", sp);
            }
            else
            {
                return RedirectToAction("Dash", "ProductUpdateVMs");
            }
        }

        // GET: SideProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SideProduct sideProduct = db.SideProducts.Find(id);
            if (sideProduct == null)
            {
                return HttpNotFound();
            }
            return View(sideProduct);
        }

        // GET: SideProducts/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: SideProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SideID,SideName,SideShort,SideBody")] SideProduct sideProduct)
        {
            try
            {
                HttpPostedFileBase file = Request.Files["ImageData"];
                ContentRepository service = new ContentRepository();
                sideProduct = service.UploadImageInDataBase(file, sideProduct);
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting  
                        // the current instance as InnerException  
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
            if (ModelState.IsValid)
            {
                db.SideProducts.Add(sideProduct);
                db.SaveChanges();
                return RedirectToAction("Dash", "ProductUpdateVMs");
            }

            return View(sideProduct);

        }

        // GET: SideProducts/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SideProduct sideProduct = db.SideProducts.Find(id);
            if (sideProduct == null)
            {
                return HttpNotFound();
            }
            return View(sideProduct);
        }

        // POST: SideProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SideID,SideName,SideShort,SideBody")] SideProduct sideProduct)
        {
            try
            {
                HttpPostedFileBase file = Request.Files["ImageData"];
                ContentRepository service = new ContentRepository();
                sideProduct = service.UploadImageInDataBase(file, sideProduct);
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting  
                        // the current instance as InnerException  
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }

            if (ModelState.IsValid)
            {
                db.Entry(sideProduct).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sideProduct);
        }

        // GET: SideProducts/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SideProduct sideProduct = db.SideProducts.Find(id);
            if (sideProduct == null)
            {
                return HttpNotFound();
            }
            return View(sideProduct);
        }

        // POST: SideProducts/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SideProduct sideProduct = db.SideProducts.Find(id);
            db.SideProducts.Remove(sideProduct);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult RetrieveImage(int id)
        {
            byte[] cover = GetImageFromDataBase(id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }
        public byte[] GetImageFromDataBase(int Id)
        {
            IQueryable<byte[]> q;

            q = from temp in db.SideProducts where temp.SideID == Id select temp.SideImage;

            byte[] cover = q.First();
            return cover;
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult UploadFile(HttpPostedFileBase aUploadedFile)
        {
            var vReturnImagePath = string.Empty;
            if (aUploadedFile.ContentLength > 0)
            {
                var vFileName = Path.GetFileNameWithoutExtension(aUploadedFile.FileName);
                var vExtension = Path.GetExtension(aUploadedFile.FileName);

                string sImageName = vFileName + DateTime.Now.ToString("YYYYMMDDHHMMSS");

                var vImageSavePath = Server.MapPath("/UpImages/") + sImageName + vExtension;
                //sImageName = sImageName + vExtension;  
                vReturnImagePath = "/UpImages/" + sImageName + vExtension;
                ViewBag.Msg = vImageSavePath;
                var path = vImageSavePath;

                // Saving Image in Original Mode  
                aUploadedFile.SaveAs(path);
                var vImageLength = new FileInfo(path).Length;
                //here to add Image Path to You Database ,  
                TempData["message"] = string.Format("Image was Added Successfully");
            }
            return Json(Convert.ToString(vReturnImagePath), JsonRequestBehavior.AllowGet);
        }
    }
}

InsightAvionics/Controllers/UpdatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InsightAvionics.Models;
using UploadAndDisplayImageInMvc.Repositories;

namespace InsightAvionics.Controllers
{
    public class UpdatesController : Controller
    {
        private InsightAvionicsContext db = new InsightAvionicsContext();

        // GET: Updates
        public ActionResult Index()
        {
            return View(db.Updates.ToList());
        }

        // GET: Updates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Update update = db.Updates.Find(id);
            if (update == null)
            {
                return HttpNotFound();
            }
            return View(update);
        }

        // GET: Updates/Create-
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Updates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UpdateID,UpdateName,UpdateBody,UpdateHeading")] Update update)
        {
            update.posted = DateTime.Now;
            try
            {
                HttpPostedFileBase file = Request.Files["ImageData"];
                ContentRepository service = new ContentRepository();
                update = service.UploadImageInDataBase(file, update);
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting  
                        // the current instance as InnerException  
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
            if (ModelState.IsValid)
            {
                List<Update> p = new List<Update> { update };
                var x = new ProductUpdateVM() { Updates = p };
                x.Updates.Add(update);

                db.ProductUpdateVMs.Add(x);
                db.SaveChanges();
                return RedirectToAction("Dash", "ProductUpdateVMs");
            }

            return View(update);
        }

        // GET: Updates/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Update update = db.Updates.Find(id);
            if (update == null)
            {
                return HttpNotFound();
            }
            return View(update);
        }

        // POST: Updates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UpdateID,UpdateName,UpdateBody,UpdateHeading")] Update update)
        {
            update.posted = DateTime.Now;
            try
            {
                HttpPostedFileBase file = Request.Files["ImageData"];
                ContentRepository service = new ContentRepository();
                update = service.UploadImageInDataBase(file, update);
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting  
                        // the current instance as InnerException  
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
            if (ModelState.IsValid)
            {
                db.Entry(update).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Dash", "ProductUpdateVMs");
            }
            return View(update);
        }

        // GET: Updates/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Update update = db.Updates.Find(id);
            if (update == null)
            {
                return HttpNotFound();
            }
            return View(update);
        }

        // POST: Updates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Update update = db.Updates.Find(id);
            db.Updates.Remove(update);
            db.SaveChanges();
            return RedirectToAction("Dash", "ProductUpdateVMs");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult RetrieveImage(int id)
        {
            byte[] cover = GetImageFromDataBase(id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }
        public byte[] GetImageFromDataBase(int Id)
        {
            IQueryable<byte[]> q;

            q = from temp in db.Updates where temp.UpdateID == Id select temp.UpdateImage;

            byte[] cover = q.First();
            return cover;
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult UploadFile(HttpPostedFileBase aUploadedFile)
        {
            var vReturnImagePath = string.Empty;
            if (aUploadedFile.ContentLength > 0)
            {
                var vFileName = Path.GetFileNameWithoutExtension(aUploadedFile.FileName);
                var vExtension = Path.GetExtension(aUploadedFile.FileName);

                string sImageName = vFileName + DateTime.Now.ToString("YYYYMMDDHHMMSS");

                var vImageSavePath = Server.MapPath("/UpImages/") + sImageName + vExtension;
                //sImageName = sImageName + vExtension;  
                vReturnImagePath = "/UpImages/" + sImageName + vExtension;
                ViewBag.Msg = vImageSavePath;
                var path = vImageSavePath;

                // Saving Image in Original Mode  
                aUploadedFile.SaveAs(path);
                var vImageLength = new FileInfo(path).Length;
                //here to add Image Path to You Database ,  
                TempData["message"] = string.Format("Image was Added Successfully");
            }
            return Json(Convert.ToString(vReturnImagePath), JsonRequestBehavior.AllowGet);
        }

    }
}

InsightAvionics/Views/ProductUpdateVMs/Create.cshtml
@model InsightAvionics.Models.ProductUpdateVM

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductUpdateVM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsightAvionics/Views/ProductUpdateVMs/Dash.cshtml
@model IEnumerable<InsightAvionics.Models.ProductUpdateVM>
@using InsightAvionics.Models;

@{
    ViewBag.Title = "Index";
    List<Update> displayed = new List<Update> { };
    Product p = new Product();
}

    <div class="row maincontent">
        
        <div class="col-md-12">
            <p>
                @Html.ActionLink("Create New Product", "Create", "Products")
            </p>
            <table class="table">
                <tr>
                    <th>
                        Product Name
                    </th>
                    <th>
                        Product Image
                    </th>
                    <th>
                        Product Description
                    </th>
                    <th>
                        Splash Image
                    </th>
                    <th>
                        Promo Image
                    </th>
                    <th>
                        Shorthand
                    </th>
                </tr>
                @foreach (var item in Model)
                {
                    foreach (var prod in item.Products)
                    {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => prod.ProdName)
                    </td>
                    <td>
                        <img src="/Products/RetrieveImage/@prod.ProdID" alt="" height=100 width=200 />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => prod.ProdDesc)
                    </td>
                    <td>
                        <img src="/Products/RetrieveImage/@prod.ProdID?type=ProdSplash" alt="" height=100 width=200 />
                    </td>
                    <td>
                        <img src="/Products/RetrieveImage/@prod.ProdID?type=ProdPromo" alt="" height=100 width=200 />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => prod.ProdShort)
                    </td>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Products", new { id = prod.ProdID }, "")
                            @*@Html.ActionLink("Details", "Details","Products", new { id = prod.ProdID },"")*@
                            <a href="/Products/@prod.ProdShort">Details</a>
                            @Html.ActionLink("Delete", "Delete", "Products", new { id = prod.ProdID }, "")
                        </td>
                    }
                </tr>

                    }
                }
            </table>
            <p>
                @Html.ActionLink("Create New Update", "Create", "Updates")
            </p>
            <table class="table">
                <tr>
                    <th>
                        Update Name
                    </th>
                    <th>
                        Update Image
                    </th>
                    <th>
                        Update Body
                    </th>
                    <th>
                        Update Posted On
                    </th>
                    <th></th>
                </tr>
                @foreach (var item in Model)
                {
                    foreach (Update up in item.Updates)
                    {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => up.UpdateName)
                    </td>
                    <td>
                        <img src="/Updates/RetrieveImage/@up.UpdateID" alt="" height=100 width=200 />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => up.UpdateBlurb)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => up.posted)
                    </td>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Updates", new { id = up.UpdateID }, "")
                            @Html.ActionLink("Details", "Details", "Updates", new { id = up.UpdateID }, "")
                            @Html.ActionLink("Delete", "Delete", "Updates", new { id = up.UpdateID }, "")
                        </td>
                    }
                </tr>
                    }


                }
            </table>

            <p>
                @Html.ActionLink("Create New Side Product", "Create", "SideProducts")
            </p>
            <table class="table">
                <tr>
                    <th>
                        Product Name
                    </th>
                    <th>
                        Product Image
                    </th>
                    <th>
                        Product Body
                    </th>
                    <th>
                        Shorthand
                    </th>
                    <th></th>
                </tr>
                @foreach (SideProduct sp in ViewBag.Side)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => sp.SideName)
                    </td>
                    <td>
                        <img src="/SideProducts/RetrieveImage/@sp.SideID" alt="" height=100 width=200 />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => sp.SideBody)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => sp.SideShort)
                    </td>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <td>
                            @Html.ActionLink("Edit", "Edit", "SideProducts", new { id = sp.SideID }, "")
                            @Html.ActionLink("Details", "Details", "SideProducts", new { id = sp.SideID }, "")
                            @Html.ActionLink("Delete", "Delete", "SideProducts", new { id = sp.SideID }, "")
                        </td>
                    }
                </tr>
                 }
            </table>

        </div>

    </div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

InsightAvionics/Views/ProductUpdateVMs/Delete.cshtml
@model InsightAvionics.Models.ProductUpdateVM

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductUpdateVM</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

InsightAvionics/Views/ProductUpdateVMs/Details.cshtml
@model InsightAvionics.Models.ProductUpdateVM

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProductUpdateVM</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

InsightAvionics/Views/ProductUpdateVMs/Index.cshtml
@model IEnumerable<InsightAvionics.Models.ProductUpdateVM>
@using InsightAvionics.Models;

@{
    ViewBag.Title = "Index";
    List<Update> displayed = new List<Update> { };
}

    <div class="row">
        <div class="col-12"></div>
        <div class="jumbotron" style="background-position:50% 85%; background-image: url('../../Assets/jumbotron.jpg')">
            <div class="splashcontainer">
                <div class="row">
                    <div class="col-md-8">
                    </div>
                    <div class="col-md-4 jumbocontent">
                        <h3><strong>About Insight</strong></h3>
                        <p>
                            The worlds first Graphic Engine Monitor was unveiled at the 1981 American Bonanza Society convention triggered a demand for the revolutionary GEM.  Insight Instrument Corporation has rapidly become the new standard in engine monitors.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>


@*<section id="hero" class="d-flex align-items-center">
        <div class="container text-center position-relative" data-aos="fade-in" data-aos-delay="200">
            <h1>Your New Online Presence with Bethany</h1>
            <h2>We are team of talanted designers making websites with Bootstrap</h2>
            <a href="#about" class="btn-get-started scrollto">Get Started</a>
        </div>
    </section>*@

<!-- End Hero -->

<div class="headings">
    <div class="row">
        <div class="col-8">
            <h2><strong>Find Your Engine Monitor</strong></h2>
        </div>
        <div class="col-4">
            <h2><strong>News & Updates</strong></h2>
        </div>
    </div>
</div>

<div class="row maincontent">

    <div class="col-md-8">
        <div class="row">
            @foreach (var item in Model)
            {
                foreach (var prod in item.Products)
                {

                    <div class="col-md-6">

                        <div class="row">
                            <div class="col">

                                @*<div><img class=" img-fluid" src=@Html.DisplayFor(modelItem => prod.ProdImage)></div>*@
                                <div><img class="img-fluid" src="/Products/RetrieveImage/@prod.ProdID" alt="" height=100 width=200 /></div>


                                <h3>@Html.DisplayFor(modelItem => prod.ProdName)</h3>

                                @*<p>@Html.DisplayFor(modelItem => prod.ProdDesc)</p>*@

                                <ul>
                                    @foreach (string s in prod.ProdBlurb)
                                    {
                                        if (!s.IsEmpty())
                                        {
                                            <li>
                                                <p>
                                                    <strong>@Html.Raw(s)</strong>
                                                </p>
                                            </li>
                                        }
                                    }
                                </ul>

                                @*<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>*@
                                <p><a class="btn btn-default" href='@Url.Action("Details", "Products", new { id = prod.ProdID })'>Learn more &raquo;</a></p>

                                @if (User.Identity.IsAuthenticated)
                                {
                                    <p>
                                        @Html.ActionLink("Edit", "Edit", "Products", new { id = prod.ProdID }, null) |
                                        @Html.ActionLink("Details", "Details", "Products", new { id = prod.ProdID }, null)  |
                                        @Html.ActionLink("Delete", "Delete", "Products", new { id = prod.ProdID }, null)
                                    </p>
                                }


                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
    <div class="col-md-4 newscontent">

        @foreach (var item in Model)
        {

            foreach (Update update in item.Updates)
            {
                displayed.Add(update);
            }
        }

        @{
            displayed.Sort(delegate (Update x, Update y)
            {
                return y.posted.CompareTo(x.posted);
            });
        }

        @for (int i = 0; i < 2; i++)
        {

            Update up = displayed.ElementAt(i);

            <h2>@Html.DisplayFor(modelItem => up.UpdateName)</h2>

            <div>

                <img class="img-fluid" align="left" src=@Html.DisplayFor(modelItem => up.UpdateImage)>
                <sub>Posted on: @Html.DisplayFor(modelItem => up.posted)</sub>

                <p>@Html.DisplayFor(modelItem => up.UpdateBlurb)</p>

                <!--<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>-->
                <p><a class="btn btn-default" href='@Url.Action("Details", "Updates", new { id = up.UpdateID })'>Learn more &raquo;</a></p>

            </div>

            if (User.Identity.IsAuthenticated)
            {
                <p>
                    @Html.ActionLink("Edit", "Edit", "Updates", new { id = up.UpdateID }, null) |
                    @Html.ActionLink("Details", "Details", "Updates", new { id = up.UpdateID }, null)  |
                    @Html.ActionLink("Delete", "Delete", "Updates", new { id = up.UpdateID }, null)
                </p>

            }
        }

        <div class="col-md-12 techsupport">
            <h2>Tech Support</h2>
            <p>
                Need Help? Reach out to us by:<br/>
                Phone:  905-871-0733<br/>
                Fax:    905-871-5460<br/>
                Email:   techsupport@insightavionics.com<br/>
                <sub>Saturdays, Sundays, and  federal holidays please leave a message. A customer service representative will contact you within 24 hours of the first business day</sub>
            </p>
            <h2>Documentation</h2>
            <p>View, print, or download any manual or STC you need <a href="google.ca">here</a></p>

            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>

        </div>
    </div>
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")